import Head from 'next/head';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Danny Caulwell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="web developer, software, software developer, .net developer, react developer"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Danny Caulwell</h1>
     
    </div>
  )
}
