import Head from 'next/head';
import Projects from '../components/Projects';
import Header from '../components/Header';
import About from '../components/About';

export default function Home() {
  return (
    <>
      <Head>
        <title>Danny Caulwell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="web developer, software, software developer, .net developer, react developer"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header 
      title="Danny Caulwell" 
      description="Graduate Software Developer"
      para="Experienced creating complex web applications with a variety of technologies"
      />

      <hr style={{width: "100%", marginTop: "1rem", opacity: "0.5"}}/>

      <About/>
     
      <Projects/>
    </>
  )
}
